# level 6 coverage : pretend to generate a coverage report

name: level_6_coverage

on: push

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Create a fake report
        run: |
          mkdir coverage
          echo "Coverage: 85%" >coverage/report.txt
      - name: Upload coverage
        uses: actions/upload-artifact@V4
        with:
           name: coverage-report
           path: coverage/
