name: Practise CI

on: 
  pull_request:

jobs:
  practise:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "welcome to the world"
      - name: lint test
        run: echo "running lint"
      - name: unit test
        run: echo "unit testing is running"
        
        
